import type { Metadata, Viewport } from "next";
import { Exo_2 as GFont } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Script from "next/script";
import ProvidersWrapper from "@/components/sdk-provider-wrapper";
import { useTelegramMock } from "@/hooks/useTelegramMock";

const gFont = GFont({
  subsets: ["latin"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "h-screen bg-black font-sans flex flex-col antialiased relative overflow-hidden",
        gFont.variable
      )}>
        {/* <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        /> */}
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        >
          <ProvidersWrapper>
            {children}
          </ProvidersWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
